-- V1__Create_initial_tables.sql
-- Criação das tabelas principais do sistema

-- Tabela de usuários para autenticação
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    enabled NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de roles (perfis de usuário)
CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) UNIQUE NOT NULL,
    description VARCHAR2(255)
);

-- Tabela de relacionamento usuário-role
CREATE TABLE usuario_roles (
    usuario_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    PRIMARY KEY (usuario_id, role_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- Tabela Patio
CREATE TABLE patio (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    logradouro VARCHAR2(255) NOT NULL,
    numero VARCHAR2(20) NOT NULL,
    cep VARCHAR2(20) NOT NULL,
    complemento VARCHAR2(100),
    cidade VARCHAR2(100) NOT NULL,
    pais VARCHAR2(100) NOT NULL,
    capacidade_maxima NUMBER NOT NULL,
    administrador_responsavel VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela Dispositivo
CREATE TABLE dispositivo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR2(50) NOT NULL,
    patio_id NUMBER,
    moto_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patio_id) REFERENCES patio(id)
);

-- Tabela Moto
CREATE TABLE moto (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imei VARCHAR2(20) UNIQUE NOT NULL,
    chassi VARCHAR2(50) NOT NULL,
    placa VARCHAR2(10) NOT NULL,
    patio_id NUMBER,
    dispositivo_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patio_id) REFERENCES patio(id)
);

-- Tabela Historico_Patio
CREATE TABLE historico_patio (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moto_id NUMBER NOT NULL,
    patio_id NUMBER NOT NULL,
    data_entrada TIMESTAMP,
    data_saida TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (moto_id) REFERENCES moto(id),
    FOREIGN KEY (patio_id) REFERENCES patio(id)
);

-- Adicionar foreign key para dispositivo na moto
ALTER TABLE dispositivo ADD CONSTRAINT fk_dispositivo_moto 
    FOREIGN KEY (moto_id) REFERENCES moto(id);